version: "3"
services:
  app:
    image: internship_23
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.18
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    expose:
      - ${MYSQL_PORT}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: